# linear algebra assignment

In [1]:
import numpy as np
import numpy.linalg as LA

## qsn-1

## Matrix operation

In [2]:
A = np.array([[2,-1],[0,3]])
B = np.array([[1,2],[-3,4]])

print(A + B)
print("-"*15)
print(A * B)
print("-"*15)
print(3*A - 2*B)

[[ 3  1]
 [-3  7]]
---------------
[[ 2 -2]
 [ 0 12]]
---------------
[[ 4 -7]
 [ 6  1]]


## Qsn-2

## Determinants and inverses

In [6]:
determinant = np.linalg.det(A)
if(determinant != 0):
    print("Inverse: ",LA.inv(A))
    print("\nDeterminant : ",determinant)
else:
    print("Unable to Calculate Determinant")

Inverse:  [[0.5        0.16666667]
 [0.         0.33333333]]

Determinant :  6.0


## Qsn-3

## Eigenvalues and Eigenvectors

In [11]:
C = np.array([[4,1],[-2,1]])
egval,egvec = np.linalg.eig(A)
print(f"The eigen values of matrix A are: {egval}")
print()
print(f"The eigen vectors of matrix A are: {egvec}")

The eigen values of matrix A are: [2. 3.]

The eigen vectors of matrix A are: [[ 1.         -0.70710678]
 [ 0.          0.70710678]]


# qsn-4

## find price of car 3

In [12]:
X = np.array([[4,1.5,100],[6,2.0,150]])
X_req = np.array([8,3.0,200])
Y = np.array([20,30])
beta = LA.pinv(X.T @ X) @ (X.T @ Y)
new_price = X_req @ beta
print("Predicted price : ",new_price)

Predicted price :  40.00000000000283
